### ISSUE TITLE
Mocha violet buttons/elements are a bit hard to read

### ISSUE THREAD

**Issue by zgibberish** [catppuccin/enmity#3]
![image](https://user-images.githubusercontent.com/67570424/196736505-70be622d-e9bb-4fc4-ac2e-53cbaea77582.png)
![image](https://user-images.githubusercontent.com/67570424/196736551-e4f39188-a4fc-4a34-aaa0-0b4fdf260d38.png)
![image](https://user-images.githubusercontent.com/67570424/196736583-da846bfe-8b11-4ad2-8a81-877f3a087320.png)
![image](https://user-images.githubusercontent.com/67570424/196736604-43c02cb5-3590-4aaa-a091-1d641c6d0527.png)
![image](https://user-images.githubusercontent.com/67570424/196736621-9bb6eaa0-fa14-425a-b010-2811dc96a5e4.png)

I think the contrast just need a little change
My suggestions are black text on violet background or just simply brighter text.

**Comment by unseen-ninja** [comment]
Good catch, and I totally agree. We tend to use either `base` or `crust` colours for text on *coloured* backgrounds. I didn't check with the other 3 themes, but it would be lovely if you could take a look at that @112cxyz? c:

**Comment by 112cxyz** [comment]
I will take a look at it and get back to you guys! Emnity themes are weird
with text but I’ll give it my best shot!
