### ISSUE TITLE
Very hard to distinguish between read and unread channels

### ISSUE THREAD

**Issue by caughtquick** [catppuccin/enmity#4]
![image](https://user-images.githubusercontent.com/62573491/197120897-ba9679c1-2bca-483f-a3cb-fff26a40bbeb.png)

The slight bolding of the text makes it only distinguishable when looking closely, unlike obviously stated due to color changes on the standard discord theme. Maybe slightly brighten and/or increase the boldness of unread channels? This is an issue across all 3 dark themes, though this screenshot was taken on Frappe.

**Comment by 112cxyz** [comment]
Alright I’ll look into it

**Comment by 112cxyz** [comment]
About to push the update should be fixed soon!

**Comment by caughtquick** [comment]
Not perfect but a lot better, thanks :)

**Comment by caughtquick** [comment]
Do you mind if I make a fork with some changes?

**Comment by 112cxyz** [comment]
It’s mainly due to a limitation in enmity itself I’ve been bashing my head
at for the past 4 hours. Also just fixing macchiato because it’s decided to
inherit colours from frappe

**Comment by 112cxyz** [comment]
Yeah i dont mind if you manage to fix it just open a PR
