### ISSUE TITLE
UPDATE: Emnity

### ISSUE THREAD

**Issue by 112cxyz** [catppuccin/enmity#8]
Hello all! I am going to be remaking the theme again because it has not been tested much with the newer versions of discord. I am continuing to maintain Emnity and if any updates are needed please create a issue and mention @112cxyz 

Thank you all!

**Comment by 112cxyz** [comment]
As you can see some UI elements are broken, ignore grey boxes they are redacted DMS
![image](https://github.com/catppuccin/enmity/assets/78795456/0024a9f5-76c6-4913-981a-d91eb63f557f)

![image](https://github.com/catppuccin/enmity/assets/78795456/acdf113c-2089-4981-a685-ab3ad9cbaed4)

**Comment by itzTheMeow** [comment]
Any update on this?

**Comment by sgoudham** [comment]
Hey there @itzTheMeow,

This repository is going to be archived soon as per #10. We have updated the theme for enmity which now lives over at [catppuccin/vendetta](https://github.com/catppuccin/vendetta). 

Please follow the instructions over there to update your theme, thanks!
